export const FETCH_DATA_LIST_SUCCESS = 'FETCH_DATA_LIST_SUCCESS';
export const FETCH_DATA_LIST_LOADING = 'FETCH_DATA_LIST_LOADING';
export const FETCH_DATA_LIST_FAILURE = 'FETCH_DATA_LIST_FAILURE';

export const FETCH_DATA_FILTER_SUCCESS = 'FETCH_DATA_FILTER_SUCCESS';
export const FETCH_DATA_FILTER_LOADING = 'FETCH_DATA_FILTER_LOADING';
export const FETCH_DATA_FILTER_FAILURE = 'FETCH_DATA_FILTER_FAILURE';

export const FETCH_DATA_BY_ID_SUCCESS = 'FETCH_DATA_BY_ID_SUCCESS';
export const FETCH_DATA_BY_ID_LOADING = 'FETCH_DATA_BY_ID_LOADING';
export const FETCH_DATA_BY_ID_FAILURE = 'FETCH_DATA_BY_ID_FAILURE';
